server:
  port: 8090
  servlet:
    session:
      timeout: 2592000

spring:
  application:
    name: gdapi-gateway
  cloud:
    gateway:
      routes:
        - id: api_order_route
          uri: lb://gdapi-order
          predicates:
            - Path=/api/order/**
#          filters:
#            - RemoveResponseHeader=Set-Cookie
        - id: api_third_route
          uri: lb://gdapi-third-party
          predicates:
              - Path=/api/third/**
        - id: path_route
          uri: lb://gdapi-backend
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source, gaoda
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
  redis:
    database: 1
    host: 192.168.174.100
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 123456
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo
    qosEnableL: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: nacos://localhost:8848



