spring:
  application:
    name: gdapi-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdapi
    username: root
    password: abc123
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    database: 1
    host: 192.168.174.100
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

server:
  port: 9001
  servlet:
    context-path: /api/order
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认为 0）

dubbo:
  application:
    name: dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: nacos://localhost:8848